sudo: required
language: bash
services:
  - docker
before_install:
  # - sudo apt-get update
  # - sudo apt-get install -y wget git
  # - sudo apt-get remove docker-ce
  # - echo "deb [arch=amd64 trusted=yes] http://ftp.unicamp.br/pub/linuxpatch/ubuntu/14_04/misc/docker-17.04.0-ce-amd64/ trusty main" | sudo tee /etc/apt/sources.list.d/docker-engine.list
  # - sudo apt-get update
  # - sudo apt-get install -y docker-engine
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # - QEMU_RELEASE=$(curl --silent "https://api.github.com/repos/multiarch/qemu-user-static/releases/latest" |grep '"tag_name":' |sed -E 's/.*"([^"]+)".*/\1/')
  # - wget https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_RELEASE/qemu-aarch64-static.tar.gz -O /tmp/qemu-aarch64-static.tar.gz
  # - wget https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_RELEASE/qemu-arm-static.tar.gz -O /tmp/qemu-arm-static.tar.gz
  # - wget https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_RELEASE/qemu-i386-static.tar.gz -O /tmp/qemu-i386-static.tar.gz
  # - tar zxvf /tmp/qemu-arm-static.tar.gz -C /tmp
  # - tar zxvf /tmp/qemu-i386-static.tar.gz -C /tmp
  # - git clone https://github.com/EdoFede/BaseImage-Docker.git
  # - cd BaseImage-Docker
  # # Build ARM Docker image
  # - docker build --volume type=bind,source=/tmp/qemu-arm-static,target=/usr/bin/qemu-arm-static -f Dockerfile -t edofede/baseimage-arm32v7 .
  # # Build Intel(i386) Docker image
  # - docker build --volume type=bind,source=/tmp/qemu-i386-static,target=/usr/bin/qemu-i386-static -f Dockerfile -t edofede/baseimage-i386 .
  # # Build Intel(amd64) Docker image
  # - docker build -f Dockerfile -t amd64/mysql .

install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker info |grep -i Version
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset


before_script:
  - |
    QEMU_RELEASE=$(curl --silent --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 60 "https://api.github.com/repos/multiarch/qemu-user-static/releases/latest" |grep '"tag_name":' |sed -E 's/.*"([^"]+)".*/\1/')
    if [ -z "$QEMU_RELEASE" ]; then
      QEMU_RELEASE = "v3.1.0-2"
    fi

script: 
  - make build ARCH=amd64 QEMU_RELEASE=$QEMU_RELEASE
  - make build ARCH=arm32v6 QEMU_RELEASE=$QEMU_RELEASE
  - make build ARCH=arm32v7 QEMU_RELEASE=$QEMU_RELEASE

after_script: docker images

before_deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

deploy:
  provider: script
  script: make push_docker && make manifest
  on:
    branch: master

after_deploy:
  - make push_latest
