sudo: required
language: bash
services:
  - docker

install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - docker info |grep -i Version
  - sudo service docker stop
  - sudo mkdir -p /etc/docker
  - sudo touch /etc/docker/daemon.json
  - echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker start
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

before_script:
  - |
    QEMU_RELEASE=$(curl -u EdoFede:$GITHUB_TOKEN --silent --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 60 "https://api.github.com/repos/multiarch/qemu-user-static/releases/latest" |grep '"tag_name":' |sed -E 's/.*"([^"]+)".*/\1/')
    if [ -z "$QEMU_RELEASE" ]; then
      QEMU_RELEASE = "v3.0.0"
    fi

script: 
  - make build ARCH=amd64 QEMU_RELEASE=$QEMU_RELEASE
  - make build ARCH=arm32v6 QEMU_RELEASE=$QEMU_RELEASE
  - make build ARCH=arm32v7 QEMU_RELEASE=$QEMU_RELEASE

after_script: docker images

before_deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

deploy:
  provider: script
  script: make push_docker && make manifest
  on:
    branch: master

after_deploy:
  - make push_latest

addons:
  apt:
    packages:
      - docker-ce

