#!/bin/sh
set -eu
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

echo "Stopping services..."
sv -w196 force-stop /etc/service/*
sv exit /etc/service/*

for PID in $(ps -eo "pid,stat" |grep "Z" |tr -d " " |sed "s/.$//" |sed "1d"); do
	timeout 5 /bin/sh -c "kill $PID && wait $PID || kill -9 $PID"
done
