#!/usr/bin/env bash
set -eu
exec 2>&1

if [ ! -S /dev/log ]; then rm -f /dev/log; fi
if [ ! -S /var/lib/syslog-ng/syslog-ng.ctl ]; then rm -f /var/lib/syslog-ng/syslog-ng.ctl; fi

CMD=/usr/sbin/syslog-ng
PID=/run/syslog-ng/syslog-ng.pid
PERSIST=/run/syslog-ng/syslog-ng.persist

install -d ${PID%/*}

exec ${CMD} --pidfile $PID --persist-file $PERSIST --foreground
